// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbjszylwlltzvhvxitic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRianN6eWx3bGx0enZodnhpdGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzk0MTQsImV4cCI6MjA3NDAxNTQxNH0.MeVbf6G_wpgL8bu2EErhPwczeqXeL_hXbfgNhpvHn7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});